ToyAppChina/Models/ApplicationDbContext.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ToyAppChina.Models
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext() : base("DefaultConnection")
        {
        }

        public DbSet<Movie> Movies { get; set; }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

ToyAppChina/Models/ApplicationUser.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ToyAppChina.Models
{
    public class ApplicationUser : IdentityUser
    {
        public string FullName { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }

    }
}

ToyAppChina/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToyAppChina.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public string Director { get; set; }
        public string Plot { get; set; }
    }
}

ToyAppChina/Models/SignupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToyAppChina.Models
{
    public class SignupViewModel
    {
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
    }
}

ToyAppChina/Controllers/AccountController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ToyAppChina.Models;

namespace ToyAppChina.Controllers
{
    public class AccountController : Controller
    {
        [Route("account/signup")]
        public ActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        [Route("account/signup")]
        public async Task<ActionResult> Signup(SignupViewModel model)
        {
            var user = new ApplicationUser
            {
                UserName = model.Email,
                Email = model.Email,
                FullName = model.FullName
            };

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var result = await userManager.CreateAsync(user, model.Password);
            //return Json(result);
            return Content("You have signed up successfully.");
        }
    }
}

ToyAppChina/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToyAppChina.Models;

namespace ToyAppChina.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Route("movies")]
        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        [Route("movies/details/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [Route("movies/create")]
        public ActionResult Create()
        {
            return View();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("movies/create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Year,Director,Plot")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        [Route("movies/edit/{id}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("movies/edit/{id}")]
        public ActionResult Edit([Bind(Include = "ID,Title,Year,Director,Plot")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        [Route("movies/delete/{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [Route("movies/delete/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToyAppChina/Controllers/StaticPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToyAppChina.Models;

namespace ToyAppChina.Controllers
{
    public class StaticPagesController : Controller
    {
        [Route("")]
        public ActionResult Home()
        {
            return View();
        }

        [Route("help")]
        public ActionResult Help()
        {
            return View();
        }

        [Route("about")]
        public ActionResult About()
        {
            return View();
        }

        [Route("contact")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

ToyAppChina/Views/Movies/Create.cshtml
@model ToyAppChina.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director)
                @Html.ValidationMessageFor(model => model.Director)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Plot)
                @Html.ValidationMessageFor(model => model.Plot)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ToyAppChina/Views/Movies/Delete.cshtml
@model ToyAppChina.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plot)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToyAppChina/Views/Movies/Details.cshtml
@model ToyAppChina.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plot)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToyAppChina/Views/Movies/Edit.cshtml
@model ToyAppChina.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director)
                @Html.ValidationMessageFor(model => model.Director)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Plot)
                @Html.ValidationMessageFor(model => model.Plot)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ToyAppChina/Views/Movies/Index.cshtml
@model IEnumerable<ToyAppChina.Models.Movie>

@{
  ViewBag.Title = "Movies";
}

<h1>Movies</h1>

<p>
  @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Title)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Year)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Director)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Title)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Year)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Director)
      </td>
      <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
      </td>
    </tr>
  }
</table>

ToyAppChina/Views/Shared/_Footer.cshtml
<footer class="footer">
  <small>
    Copyright &copy; Guoxin @DateTime.Now.Year
  </small>
  <nav>
    <ul>
      <li>@Html.ActionLink("About", "About", "StaticPages")</li>
      <li>@Html.ActionLink("Contact", "Contact", "StaticPages")</li>
      <li><a href="http://www.asp.net/whats-new">News</a></li>
    </ul>
  </nav>
</footer>

ToyAppChina/Views/Shared/_Header.cshtml
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    @Html.ActionLink("Guoxin homework", "Home", "StaticPages", null, new { id = "logo" })

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Home", "Home", "StaticPages")</li>
        <li>@Html.ActionLink("Help", "Help", "StaticPages")</li>
        <li><a href="#">Log in</a></li>
      </ul>
    </nav>
  </div>
</header>

ToyAppChina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <title>@ViewBag.Title | Guoxin homework</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
  </head>
  <body>
    @Html.Partial("_Header")
    <div class="container">
      @RenderBody()
      @Html.Partial("_Footer")
    </div>
  </body>
</html>

ToyAppChina/Views/StaticPages/About.cshtml
@{
  ViewBag.Title = "About";
}

<h1>About</h1>
<p>
  This is a sample web site built with ASP.NET MVC.
</p>

ToyAppChina/Views/StaticPages/Contact.cshtml
@{
  ViewBag.Title = "Contact";
}

<h1>Contact</h1>

<p>You can contact me at <a href="mailto:guoxin.liu@software.dell.com">guoxin.liu@software.dell.com</a>.</p>

ToyAppChina/Views/StaticPages/Help.cshtml
@{
  ViewBag.Title = "Help";
}

<h1>Help</h1>
<p>
  Get help on the ASP.NET MVC at the
  <a href="http://www.asp.net/">ASP.NET website</a>.
</p>

ToyAppChina/Views/StaticPages/Home.cshtml
@{
  ViewBag.Title = "Home";
}

<div class="center jumbotron">
  <h1>Welcome to Guoxin's homework</h1>
 
  <h2>
    This is the home page for Guoxin's homework.
  </h2>
 
  @Html.ActionLink("Sign up now!", "Signup", "Account", null, new { @class = "btn btn-lg btn-primary" })
</div>

<img src="~/Content/Images/001.png" alt="Guoxin" />